server:
  port: 2001

spring:
  application:
    name: tf-client-service
  cloud:
    config:
      name: config
      profile: dev
      label: master
      discovery:
        enabled: true
        service-id: config-service #server端的应用名
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:2004/eureka

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5

mybatis:
  type-aliases-package: com.xft.model
  mapper-locations: classpath*:/com/xft/dao/mapper/*Mapper.xml


